#!/usr/bin/env bash

# Init payment test request
curl -v -X POST localhost:15100/session/init/payment \
    -H 'Content-Type: application/json' \
    --data-raw '

    {
        "notification_url": "http://localhost:8000/app1/notification",
        "success_url": "http://localhost:8000/app1/success",
        "fail_url": "http://localhost:8000/app1/fail",
        "amount": 123,
        "beneficiaries": {
            "beneficiaries": []
        },
        "token": "802f6f4cbb6f4c3e14cd60e5bc3ab2aa455c9c12369afd01443edc973221ce4c"
    }'

curl -v -X POST --location "http://172.18.0.6:15100/session/init/card_token_reg" \
    -H "Content-Type: application/json" \
    --data-raw '

        {
            "notification_url":"https://docker.com",
            "success_url":"https://google.com",
            "fail_url":"https://yandex.ru",
            "token":"be145315f24023418aba56f116caa7327505ca5f0416ec4af2a4e948f7234e76"
        }'
