#!/usr/bin/env bash

# Init payment test request
curl -v -X POST localhost:15100/session/init/payment \
    -H 'Content-Type: application/json' \
    --data-raw '

    {
        "notification_url": "http://localhost:8000/app1/notification",
        "success_url": "http://localhost:8000/app1/success",
        "fail_url": "http://localhost:8000/app1/fail",
        "amount": 123,
        "beneficiaries": {
            "beneficiaries": []
        },
        "token": "802f6f4cbb6f4c3e14cd60e5bc3ab2aa455c9c12369afd01443edc973221ce4c"
    }'

curl -X POST --location "http://localhost:15100/api/InitCardTokenRegistration" \
    -H "Content-Type: application/json" \
    --data-raw '

        {
            "notification_url":"https://docker.com",
            "success_url":"https://google.com",
            "fail_url":"https://yandex.ru",
            "token":"8de3c11509eba15d042d0bddf9457a4f2ea90379676aa88b42a024fbf679ca19"
        }'
