#!/usr/bin/env bash

password=$1

docker run --name banksim-pg -d -v banksim-pg-data:/var/lib/postgresql/data -e POSTGRES_USER=postgres -e POSTGRES_DB=banksim -e POSTGRES_PASSWORD=$password postgres:16.2-alpine3.19
