#!/usr/bin/env bash

docker run -d --network mynet --ip 172.18.0.6 -v ./secrets:/app/secrets --name banksim -e BANKSIM_CONFIG_FILE="/app/secrets/config.yaml" -e TERMINAL_PASSWORD_FILE="/app/secrets/terminal_password.txt" -e POSTGRES_PASSWORD_FILE="/app/secrets/postgres_password.txt" -e DATA_BACKEND_TYPE="postgres" ghashy/banksim:0.1 
